name: pr-check

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@2

      - name: Lint Playbook
        uses: ansible/ansible-lint-action@master
        with:
          targets: |
            setup-infra.yaml
            start-docker-jenkins-container.yaml
            teardown-infra.yaml
        


 