name: pr-check

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/cache@v2
        with:
          path: ansible/ansible-lint-action
          key: cache

      - uses: ansible/ansible-lint-action@master
        with:
          targets: |
            /github/workspace/setup-infra.yaml
            /github/workspace/start-docker-jenkins-container.yaml
            /github/workspace/teardown-infra.yaml
          # args: "-x 204 -x 301 -x 305"